"""empty message

Revision ID: 40131cbf17f3
Revises: 9c000ac6bd7a
Create Date: 2023-12-19 23:13:30.439221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40131cbf17f3'
down_revision = '9c000ac6bd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_fav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_fav')
    # ### end Alembic commands ###
